[package]
name = "color-blender-rs"
version = "0.3.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
rayon = "1.8"
clap = { version = "4.4.13", features = ["derive"] }